common: &common
  adapter: postgresql
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  port: <%= ENV['DB_PORT'] || "5432" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development: &development
  <<: *common
  database: <%= ENV['DEV_DATABASE'] %>

test:
  <<: *common
  database: mmjeans_api_test

production:
  url: <%= ENV['DATABASE_CONNECTION_POOL_URL'] || ENV['DATABASE_URL'] %>
  prepared_statements: false
  advisory_locks: false
  statement_timeout: <%= ENV.fetch("RAILS_STATEMENT_TIMEOUT") { 5000 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
